services:
  # Build shared packages first
  shared-packages:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    command: >
      bash -c "bun install && 
              cd packages/utils && bun run build &&
              cd ../sdk && bun run build &&
              cd ../config && bun run build &&
              cd ../agents && bun run build"
    networks:
      - augmentos-network-staging
    environment:
      - SERVICE_NAME=shared-packages

  # Cloud service
  cloud:
    stop_grace_period: 10s
    init: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: ${CLOUD_PORT:-9002}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=cloud
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: bash -c "bun install && cd packages/cloud && bun run build && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - shared-packages
    labels:
      com.datadoghq.ad.logs: '[{"source": "cloud", "service": "cloud"}]'

  # Live Captions service
  live-captions:
    stop_grace_period: 5s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${LIVE_CAPTIONS_PORT:-9010}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=live-captions
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/livecaptions && bun run build && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "live-captions", "service": "live-captions"}]'

  # Flash service
  flash:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${FLASH_PORT:-9011}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=flash
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/flash && bun run build && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "flash", "service": "flash"}]'

  # Dashboard Manager service
  dashboard-manager:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${DASHBOARD_MANAGER_PORT:-9012}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=dashboard-manager
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/dashboard-manager && bun run build && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "dashboard-manager", "service": "dashboard-manager"}]'

  # Notifications service
  notify:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${NOTIFY_PORT:-9014}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=notify
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/notify && bun run build && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "notify", "service": "notify"}]'

  # Mira AI service
  mira:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${MIRA_PORT:-9015}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=mira
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/miraai && bun run build && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "mira", "service": "mira"}]'

  live-translation:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${LIVE_TRANSLATION_PORT:-9017}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=live-translation
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/livetranslation && bun run build && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "live-translation", "service": "live-translation"}]'

networks:
  augmentos-network-staging:
    driver: bridge
    external: true

volumes:
  node_modules: