services:
  augmentos-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: augmentos-cloud-dev
    restart: unless-stopped
    ports:
      - "8002:8002"  # Cloud service
      - "8010:8010"  # Live Captions
      - "8011:8011"  # Flash
      - "8012:8012"  # Dashboard
      - "8013:8013"  # Agent Gatekeeper
      - "8014:8014"  # Notifications
      - "8015:8015"  # Mira AI
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CLOUD_VERSION=1.0.0
      # MongoDB
      - MONGO_URL=mongodb://mongodb:27017/augmentos
      # Sentry
      - SENTRY_DSN=${SENTRY_DSN}
      # Azure Speech
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      # LLM Configuration
      - LLM_PROVIDER=azure
      - LLM_MODEL=gpt-4o
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_INSTANCE_NAME=${AZURE_OPENAI_API_INSTANCE_NAME}
      - AZURE_OPENAI_API_DEPLOYMENT_NAME=${AZURE_OPENAI_API_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_VERSION=2023-05-15
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Search API
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      # JWT Secrets
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - AUGMENTOS_AUTH_JWT_SECRET=${AUGMENTOS_AUTH_JWT_SECRET}
      - JOE_MAMA_USER_JWT=${JOE_MAMA_USER_JWT}
      # PostHog
      - POSTHOG_PROJECT_API_KEY=${POSTHOG_PROJECT_API_KEY}
      - POSTHOG_HOST=https://app.posthog.com
    env_file:
      - .env
    volumes:
      # Mount local source code for development (optional)
      # - ./packages:/app/packages
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - augmentos-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: augmentos-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - augmentos-network

networks:
  augmentos-network:
    driver: bridge

volumes:
  mongodb-data: 