services:

  cloud:
    stop_grace_period: 10s
    init: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: ${CLOUD_PORT:-9002}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=cloud
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: bash -c "cd packages/cloud && bun run start"
    networks:
      - augmentos-network-staging

  # Live Captions service
  live-captions:
    stop_grace_period: 5s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${LIVE_CAPTIONS_PORT:-9010}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=live-captions
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/livecaptions && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - cloud

  # Dashboard Manager service
  dashboard-manager:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${DASHBOARD_MANAGER_PORT:-9012}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=dashboard-manager
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/dashboard-manager && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - cloud

  # Notifications service
  notify:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${NOTIFY_PORT:-9014}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=notify
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/notify && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - cloud

  # Mira AI service
  mira:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${MIRA_PORT:-9015}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=mira
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/miraai && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - cloud

  live-translation:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 80
        published: ${LIVE_TRANSLATION_PORT:-9017}
        protocol: tcp
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
      - SERVICE_NAME=live-translation
    env_file:
      - .env
      - .env.staging
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/livetranslation && bun run start"
    networks:
      - augmentos-network-staging
    depends_on:
      - cloud

networks:
  augmentos-network-staging:
    driver: bridge
    external: true

volumes:
  node_modules: