services:
  # Build shared packages first
  shared-packages:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
    command: >
      bash -c "bun install --no-link && 
              cd packages/utils && bun run build &&
              cd ../config && bun run build &&
              cd ../sdk && bun run build &&
              cd ../agents && bun run build"
    networks:
      - augmentos-network-dev
    environment:
      - SERVICE_NAME=shared-packages

  # Cloud service
  cloud:
    stop_grace_period: 10s
    init: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8002:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SERVICE_NAME=cloud
      - CONTAINER_ENVIRONMENT=true
      - CLOUD_HOST_NAME=cloud
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
    command: bash -c "cd packages/cloud && bun run dev"
    networks:
      - augmentos-network-dev
    depends_on:
      - shared-packages
    labels:
      com.datadoghq.ad.logs: '[{"source": "cloud", "service": "cloud"}]'

  # Live Captions service - using external repo
  # live-captions:
  #   stop_grace_period: 5s
  #   init: true
  #   build:
  #     context: ../../Apps/Live-Captions
  #     dockerfile: Dockerfile.dev
  #   container_name: live-captions
  #   restart: unless-stopped
  #   ports:
  #     - "8020:80"
  #   environment:
  #     - PORT=80
  #     - CLOUD_HOST_NAME=cloud
  #     - NODE_ENV=development
  #   volumes:
  #     - ../../Apps/Live-Captions/src:/app/src:delegated
  #     - ../../Apps/Live-Captions/tsconfig.json:/app/tsconfig.json:delegated
  #     - ../../Apps/Live-Captions/dev.sh:/app/dev.sh:delegated
  #     - ../../Apps/Live-Captions/entrypoint.sh:/app/entrypoint.sh:delegated
  #     - ../../Apps/Live-Captions/package.json:/app/package.json:delegated
  #     - ../../AugmentOS/augmentos_cloud/node_modules/@augmentos:/app/node_modules/@augmentos:delegated
  #     # Don't sync node_modules back to host
  #     - /app/node_modules
  #   command: ["bash", "/app/entrypoint.sh"]
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - augmentos-network-dev
  #   depends_on:
  #     - shared-packages
  #     - cloud
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   labels:
  #     com.datadoghq.ad.logs: '[{"source": "live-captions", "service": "live-captions"}]'

  # Flash service
  flash:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8011:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SERVICE_NAME=flash
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/flash && bun run dev"
    networks:
      - augmentos-network-dev
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "flash", "service": "flash"}]'

  # Dashboard Manager service
  dashboard-manager:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8012:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SERVICE_NAME=dashboard-manager
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/dashboard-manager && bun run dev"
    networks:
      - augmentos-network-dev
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "dashboard-manager", "service": "dashboard-manager"}]'

  # Notifications service
  notify:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8014:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SERVICE_NAME=notify
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/notify && bun run dev"
    networks:
      - augmentos-network-dev
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "notify", "service": "notify"}]'

  # Mira AI service
  mira:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8015:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SERVICE_NAME=mira
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/miraai && bun run dev"
    networks:
      - augmentos-network-dev
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "mira", "service": "mira"}]'

  live-translation:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8017:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SERVICE_NAME=live-translation
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/livetranslation && bun run dev"
    networks:
      - augmentos-network-dev
    depends_on:
      - shared-packages
      - cloud
    labels:
      com.datadoghq.ad.logs: '[{"source": "live-translation", "service": "live-translation"}]'

  # merge:
  #   # Use local development setup for MentraMerge
  #   build:
  #     context: ../../AugmentApps/MentraMerge  # Path to the MentraMerge repo
  #     dockerfile: Dockerfile.dev
  #   container_name: merge
  #   ports:
  #     - "8016:80"
  #   environment:
  #     - PORT=80
  #     - CLOUD_HOST_NAME=cloud
  #     - NODE_ENV=development
  #     - MERGE_API_KEY=${MERGE_API_KEY:-test_key}
  #   volumes:
  #     - ../../Apps/MentraMerge/src:/app/src:delegated
  #     - ../../Apps/MentraMerge/tsconfig.json:/app/tsconfig.json:delegated
  #     - ../../Apps/MentraMerge/dev.sh:/app/dev.sh:delegated
  #     - ../../Apps/MentraMerge/entrypoint.sh:/app/entrypoint.sh:delegated
  #     - ../../Apps/MentraMerge/package.json:/app/package.json:delegated
  #     - ../../AugmentOS/augmentos_cloud/node_modules/@augmentos:/app/node_modules/@augmentos:delegated
  #     # Don't sync node_modules back to host
  #     - /app/node_modules
  #   command: ["bash", "/app/entrypoint.sh"]
  #   restart: "no"
  #   stdin_open: true
  #   tty: true
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   depends_on:
  #     - shared-packages
  #     - cloud
  #   networks:
  #     - augmentos-network-dev


  # AugHog TPA
  # aughog:
  #   build:
  #     context: ../../Apps/AugHog
  #     dockerfile: docker/Dockerfile.dev
  #   container_name: aughog
  #   ports:
  #     - "8030:80"
  #   environment:
  #     - PORT=80
  #     - CLOUD_HOST_NAME=cloud
  #     - NODE_ENV=development
  #   volumes:
  #     - ../../Apps/AugHog:/app
  #     - /app/node_modules
  #   command: sh -c "bun install && bun --hot --watch src/index.ts"
  #   networks:
  #     - augmentos-network-dev
  #   depends_on:
  #     - cloud
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

networks:
  augmentos-network-dev:
    driver: bridge
    external: true
    name: augmentos-network-dev

volumes:
  node_modules:
  bun_cache: