services:
  # Build shared packages first
  shared-packages:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    command: >
      bash -c "bun install && 
              cd packages/utils && bun run build &&
              cd ../sdk && bun run build &&
              cd ../agents && bun run build"
    networks:
      - augmentos-network

  # Cloud service
  cloud:
    stop_grace_period: 10s  # Allow only 10 seconds for graceful shutdown
    init: true  # Use an init process to handle signal forwarding
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8002:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: bash -c "bun install && cd packages/cloud && bun run dev"
    networks:
      - augmentos-network
    depends_on:
      - shared-packages

  # Live Captions service
  live-captions:
    stop_grace_period: 10s  # Allow only 10 seconds for graceful shutdown
    init: true  # Use an init process to handle signal forwarding
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8010:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/livecaptions && bun run dev"
    networks:
      - augmentos-network
    depends_on:
      - shared-packages
      - cloud

  # Flash service
  flash:
    stop_grace_period: 10s  # Allow only 10 seconds for graceful shutdown
    init: true  # Use an init process to handle signal forwarding
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8011:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/flash && bun run dev"
    networks:
      - augmentos-network
    depends_on:
      - shared-packages
      - cloud

  # Dashboard Manager service
  dashboard-manager:
    stop_grace_period: 10s  # Allow only 10 seconds for graceful shutdown
    init: true  # Use an init process to handle signal forwarding
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8012:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/dashboard-manager && bun run dev"
    networks:
      - augmentos-network
    depends_on:
      - shared-packages
      - cloud

  # Notifications service
  notify:
    stop_grace_period: 10s  # Allow only 10 seconds for graceful shutdown
    init: true  # Use an init process to handle signal forwarding
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8014:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/notify && bun run dev"
    networks:
      - augmentos-network
    depends_on:
      - shared-packages
      - cloud

  # Note Merge runs in a separate repo.

  # Mira AI service
  mira:
    stop_grace_period: 10s  # Allow only 10 seconds for graceful shutdown
    init: true  # Use an init process to handle signal forwarding
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8015:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/miraai && bun run dev"
    networks:
      - augmentos-network
    depends_on:
      - shared-packages
      - cloud
  live-translation:
    stop_grace_period: 10s  # Allow only 10 seconds for graceful shutdown
    init: true  # Use an init process to handle signal forwarding
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8017:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/livetranslation && bun run dev"
    networks:
      - augmentos-network
    depends_on:
      - shared-packages
      - cloud
  isaiah:
    stop_grace_period: 10s  # Allow only 10 seconds for graceful shutdown
    init: true  # Use an init process to handle signal forwarding
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "42022:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./logs:/app/logs
    command: bash -c "bun install && cd packages/apps/isaiah && bun run dev"
    networks:
      - augmentos-network
    depends_on:
      - shared-packages
      - cloud

networks:
  augmentos-network:
    driver: bridge

volumes:
  node_modules: